### ISSUE TITLE
[FEAT] 누적 커피 잔 수 확인하기

### ISSUE THREAD

**Issue by alveloper** [team-mokcha/corabal-beta#12]
## 📔   개요
프로필 스크린에서 유저가 기록했던 누적 커피 잔수를 보여주는 기능입니다.

## ✅    작업 사항

**백엔드**
- [x] users 컬렉션에 유저 이메일로 만든 각 다큐먼트의 필드에 every_cup_of_coffee 필드 생성
  - 10.02 users 컬렉션의 각 유저마다 total_cups 생성되어 있음
- [ ] is_normal_cup: true && is_zero_cup: false 일 때, normal_cup_record 배열의 길이를 구해 every_cup_of_coffee 필드에 더하기

프론트엔드
- [x] 프로필 스크린에서 누적 커피 잔 수를 보여주는 레이아웃 구현
- [x] DB에서 누적 커피 잔 수 가져와서 화면에 보여주기

## ⛑️    참고 사항
위 작업 사항은 DB에 전체 누적 커피 잔 필드가 있다는 가정 하에 작성되었습니다. 
현재는 해당 필드가 없으므로 추가할 필요가 있어 보입니다! 이것도 회원가입 시 해야 할까요? @HyejinYang

**Comment by alveloper** [comment]
여러 필드를 한꺼번에 업데이트 할 땐 반드시 batch write!

**Comment by HyejinYang** [comment]
넵! 회원가입 시 생성되어야 하는 필드에 추가하겠습니다요
