### ISSUE TITLE
[FEAT] Firestore 보안 규칙 설정

### ISSUE THREAD

**Issue by HyejinYang** [team-mokcha/corabal-beta#16]
## 📔   개요
인증된 유저의 클라이언트만 firestore에 접근 가능하도록 보안을 설정하고, DB 필드가 create/update 될 경우 데이터를 검증하도록 보안 규칙을 설정함

## ✅    작업 사항

- [x] 유저 signed-in 확인 @HyejinYang 
- [X] 유저 데이터 조건부 검증 @HyejinYang 
- [ ] 커피 로그 데이터 조건부 검증 @HyejinYang 
- [ ] 포인트 데이터 조건부 검증 @alveloper 
- [ ] 컵 데이터 조건부 검증 @alveloper

## ⛑️    참고 사항
공유할 내용, 스크린샷 등을 넣어주세요.
- 추가적인 공유가 필요한 사항은 Comment로 달아주기

1. 보안 규칙 관련해서 서로 상의가 더 필요할 수 있음~!

**Comment by HyejinYang** [comment]
@alveloper 
현재 메인 접근 시 firestore 관련 에러 메시지가 뜹니다.
user collection에서 'goal' 필드를 가져오지 못하는 건데, 보안 규칙은 현재 인증된 유저이기만 하면 되는 것으로 풀어놓은 상태라서...
DB 접근 시에 잘못 가져오는 것일 가능성이 큰데, 한 번 살펴보시는 게 좋을 것 같아요.
저도 coffee log 생성 기능 개발이 끝나는대로 알아보겠습니다. 

![image](https://user-images.githubusercontent.com/70951555/133225530-6d8ddb22-352d-42cb-9f5b-dfcb672153da.png)

**Comment by alveloper** [comment]
> @alveloper
> 현재 메인 접근 시 firestore 관련 에러 메시지가 뜹니다.
> user collection에서 'goal' 필드를 가져오지 못하는 건데, 보안 규칙은 현재 인증된 유저이기만 하면 되는 것으로 풀어놓은 상태라서...
> DB 접근 시에 잘못 가져오는 것일 가능성이 큰데, 한 번 살펴보시는 게 좋을 것 같아요.
> 제 쪽에서 뭔가 잘못한 것일 수도 있으니, 저도 coffee log 생성 기능 개발이 끝나는대로 알아보겠습니다.
> 
> ![image](https://user-images.githubusercontent.com/70951555/133225530-6d8ddb22-352d-42cb-9f5b-dfcb672153da.png)

이거 오늘 제가 하면서 일단 권한 다 풀어놓는 걸로 바꿔놨습니다!
권한은 같이 한 번 설정해보는 게 어떨까요?
![image](https://user-images.githubusercontent.com/73899253/133990252-078017fd-8d11-4a57-9551-625fa6d7fdd8.png)

**Comment by HyejinYang** [comment]
* 보안 규칙 이슈 해결되었음
