### ISSUE TITLE
[REFACTOR] Atomic design pattern 적용

### ISSUE THREAD

**Issue by alveloper** [team-mokcha/corabal-beta#38]
## 📔   리팩토링 이유
- 폴더 구조를 아토믹 디자인 패턴에 맞춰 변경
- 리액트의 컨셉인 '재사용 가능하고 독립적인 컴포넌트'에 맞춰 리팩토링
- atoms -> molecules -> organisms -> templates -> pages
- 폴더 구조는 하단 링크 참고해서 적용

## ⛑️    참고 사항
[링크 1](https://velog.io/@thsoon/%EC%93%B8%EB%95%8C%EC%97%86%EC%9D%B4-%EA%B3%A0%ED%80%84%EC%9D%B8-%ED%88%AC%EB%91%90%EB%A6%AC%EC%8A%A4%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-FE-2.-%EB%B7%B0-%EC%84%A4%EA%B3%84) 
[링크 2](https://github.com/dlatns0201/prography_6th_react)

**Comment by alveloper** [comment]
rule:
organisms: 섹션이 두가지 이상이거나 / 반복은 되지 않더라도 다른 템플릿에서 동일한 섹션을 쓰고 있을 때

**Comment by alveloper** [comment]
모달에 들어가야 할 내용은 각자 템플릿에서 만들기!

**Comment by HyejinYang** [comment]
리팩 완료! @alveloper 고생하셨습니다! 🤟
