### ISSUE TITLE
[REFACTOR] 레코드 스크린에 전역 state 관리 적용

### ISSUE THREAD

**Issue by alveloper** [team-mokcha/corabal-beta#45]
## 📔   리팩토링 이유
- prop drilling이 너무 극심해서 (4번 이상) 바꾸려고요..

## ✅    작업 사항
- [x] hookState로 전역변수 만들기 (프론트 view change, 백엔드로 보내는 로직)
- [x] 만든 전역변수를 atom 단위의 컴포넌트에서 바로 사용

**Comment by HyejinYang** [comment]
![image](https://user-images.githubusercontent.com/70951555/142581842-f56e4879-b5ca-466e-8764-014837f7ae5f.png)

**Comment by HyejinYang** [comment]
완료!
