### ISSUE TITLE
[FEAT] 당일 등록한 커피 기록 수정

### ISSUE THREAD

**Issue by alveloper** [team-mokcha/corabal-beta#9]
## 📔   개요
1. 유저가 이미 등록한 커피 기록을 수정할 수 있는 기능입니다.
2. 이때 수정은 기록의 삭제를 의미합니다.

## ✅    작업 사항

**백엔드**
- [ ] is_recorded - is_normal_cup: false, is_zero_cup: false && normal_cup_record 배열의 길이가 1 이상일 때만 삭제하기
- [ ] 유저가 선택한 기록을 DB에서 삭제하기

**프론트엔드**
- [x] 메인 스크린에서 커피 기록 수정 버튼 레이아웃 짜기
- [ ] 커피 기록이 있을 때만 메인 스크린에서 수정 버튼 활성화
- [ ] DB에서 당일 커피 기록을 가져와 화면에 보여주기
- [ ] 유저가 삭제할 특정 기록을 선택했을 때 DB에 해당 기록 전달하기

**기획**
- [ ] 삭제 버튼을 눌렀을 때 화면에서 그 기록이 사라지는지 또는 그대로인지 등의 UI 변화 확인하기
- [ ] 확인 버튼을 눌러야지만 기록이 삭제되는 기능인지 확인하기

## ⛑️    참고 사항
공유할 내용, 스크린샷 등을 넣어주세요.
- 추가적인 공유가 필요한 사항은 Comment로 달아주기

**Comment by HyejinYang** [comment]
이 기능은 내가 담당하기로 결정~! 2021.09.15 회의 기록 참고하기~!
